# Generated by Django 4.1.1 on 2022-09-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descriptions_az',
            field=models.TextField(null=True, verbose_name='Description of category'),
        ),
        migrations.AddField(
            model_name='category',
            name='descriptions_en',
            field=models.TextField(null=True, verbose_name='Description of category'),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='altText_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='altText_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='hashtags_az',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='hashtags_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
