# Generated by Django 4.1.1 on 2022-09-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_descriptions_az_category_descriptions_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdoctor',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='Description of AboutDoctor'),
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Title of AboutDoctor'),
        ),
        migrations.AddField(
            model_name='category',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='Description of category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of category'),
        ),
        migrations.AddField(
            model_name='categoryaboutdoctor',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='Description of category'),
        ),
        migrations.AddField(
            model_name='categoryaboutdoctor',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of category'),
        ),
        migrations.AddField(
            model_name='imagecategory',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='altText_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='hashtags_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Title of ourservices articles'),
        ),
        migrations.AddField(
            model_name='ourservicescategory',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='Description of AboutCategory'),
        ),
        migrations.AddField(
            model_name='ourservicescategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of AboutCategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Title of post'),
        ),
    ]
