# Generated by Django 4.1.1 on 2022-09-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_category_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='altText_az',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='altText_en',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='altText_ru',
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='MetaDescriptions_az',
            field=models.CharField(max_length=500, null=True, verbose_name='MetaDescription of AboutDoctor'),
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='MetaDescriptions_en',
            field=models.CharField(max_length=500, null=True, verbose_name='MetaDescription of AboutDoctor'),
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='MetaDescriptions_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='MetaDescription of AboutDoctor'),
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='MetaKeyWords_az',
            field=models.CharField(max_length=500, null=True, verbose_name='MetKeyWords of AboutDoctor'),
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='MetaKeyWords_en',
            field=models.CharField(max_length=500, null=True, verbose_name='MetKeyWords of AboutDoctor'),
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='MetaKeyWords_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='MetKeyWords of AboutDoctor'),
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='tagline_az',
            field=models.CharField(default='', max_length=360, null=True, verbose_name='Tagline of AboutDoctor'),
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='tagline_en',
            field=models.CharField(default='', max_length=360, null=True, verbose_name='Tagline of AboutDoctor'),
        ),
        migrations.AddField(
            model_name='aboutdoctor',
            name='tagline_ru',
            field=models.CharField(default='', max_length=360, null=True, verbose_name='Tagline of AboutDoctor'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='MetaDescriptions_az',
            field=models.CharField(max_length=500, null=True, verbose_name='MetaDescription of ourservices articles'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='MetaDescriptions_en',
            field=models.CharField(max_length=500, null=True, verbose_name='MetaDescription of ourservices articles'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='MetaDescriptions_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='MetaDescription of ourservices articles'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='MetaKeyWords_az',
            field=models.CharField(max_length=500, null=True, verbose_name='MetKeyWords of ourservices articles'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='MetaKeyWords_en',
            field=models.CharField(max_length=500, null=True, verbose_name='MetKeyWords of ourservices articles'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='MetaKeyWords_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='MetKeyWords of ourservices articles'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='tagline_az',
            field=models.CharField(default='', max_length=360, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='tagline_en',
            field=models.CharField(default='', max_length=360, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='tagline_ru',
            field=models.CharField(default='', max_length=360, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='post',
            name='MetaDescriptions_az',
            field=models.CharField(max_length=500, null=True, verbose_name='MetaDescription of post'),
        ),
        migrations.AddField(
            model_name='post',
            name='MetaDescriptions_en',
            field=models.CharField(max_length=500, null=True, verbose_name='MetaDescription of post'),
        ),
        migrations.AddField(
            model_name='post',
            name='MetaDescriptions_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='MetaDescription of post'),
        ),
        migrations.AddField(
            model_name='post',
            name='MetaKeyWords_az',
            field=models.CharField(max_length=500, null=True, verbose_name='MetKeyWords of post'),
        ),
        migrations.AddField(
            model_name='post',
            name='MetaKeyWords_en',
            field=models.CharField(max_length=500, null=True, verbose_name='MetKeyWords of post'),
        ),
        migrations.AddField(
            model_name='post',
            name='MetaKeyWords_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='MetKeyWords of post'),
        ),
        migrations.AddField(
            model_name='post',
            name='tagline_az',
            field=models.CharField(default='', max_length=360, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='post',
            name='tagline_en',
            field=models.CharField(default='', max_length=360, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='post',
            name='tagline_ru',
            field=models.CharField(default='', max_length=360, null=True, verbose_name='Tagline'),
        ),
    ]
