# Generated by Django 4.1.1 on 2022-09-26 17:48

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_imagegallery_image17_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='Image17',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image18',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image19',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image20',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image21',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image22',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image23',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image24',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
    ]
