# Generated by Django 4.1.1 on 2022-09-28 12:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_imagegallery_image17_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='images_for_site/Image/%Y/%m/%d', verbose_name='Poster of DetailView'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_tur',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[200, 200], upload_to='images_for_site/Image_Tur/%Y/%m/%d', verbose_name='Poster of ListView'),
        ),
    ]
