# Generated by Django 4.1.1 on 2022-10-03 10:52

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_reviews_movie_remove_reviews_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of VideoCategory')),
                ('descriptions', models.TextField(verbose_name='Description of VideoCategory')),
                ('url', models.SlugField(max_length=160, unique=True, verbose_name='URL of VideoCategory')),
                ('MetaKeyWords', models.CharField(max_length=500, verbose_name='MetaKeywords of VideoCategory')),
                ('MetaDescriptions', models.CharField(max_length=500, verbose_name='MetaDescription of VideoCategory')),
                ('image', models.ImageField(upload_to='Video/category_video', verbose_name='Image of VideoCategory')),
            ],
            options={
                'verbose_name': 'VideoCategory',
                'verbose_name_plural': 'VideoCategory ',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='predescriptions',
        ),
        migrations.AlterField(
            model_name='aboutdoctor',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Image_About_Doctor', verbose_name='Poster of DetailView of AboutDoctor'),
        ),
        migrations.AlterField(
            model_name='aboutdoctor',
            name='image_tur',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[200, 200], upload_to='Image_tur_About_Doctor', verbose_name='Poster of ListView of PostSingle'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_post/', verbose_name='Image of category'),
        ),
        migrations.AlterField(
            model_name='categoryaboutdoctor',
            name='image',
            field=models.ImageField(upload_to='category_about_doctor/', verbose_name='Image of category'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image1',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image10',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image11',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpge', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image12',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image13',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image14',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image15',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image16',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image17',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image18',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image19',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image2',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image20',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image21',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image22',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image23',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image24',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image3',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image4',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image5',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image6',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image7',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image8',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Image9',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='ImageList',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[200, 200], upload_to='Gallery/ImageList'),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='image',
            field=models.ImageField(upload_to='ourservices/', verbose_name='Poster of ourservices articles'),
        ),
        migrations.AlterField(
            model_name='ourservicescategory',
            name='image',
            field=models.ImageField(upload_to='about_category/', verbose_name='Image of AboutCategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='Image//%Y/%m/%d', verbose_name='Poster of DetailView'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_tur',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[200, 200], upload_to='Image_Tur//%Y/%m/%d', verbose_name='Poster of ListView'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(max_length=160, unique=True, verbose_name='URL of Post'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Title of Video')),
                ('tagline', models.CharField(default='', max_length=360, verbose_name='Tagline of Video')),
                ('descriptions', models.TextField(verbose_name='Description of Video')),
                ('image_poster', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='Video/image_poster', verbose_name='Poster of DetailView')),
                ('video_youtube', models.CharField(blank=True, max_length=1155, null=True, verbose_name='Video from youtube')),
                ('video_our', models.FileField(default='default.mp4', upload_to='Video/video_our', verbose_name='Video from our server')),
                ('url', embed_video.fields.EmbedVideoField()),
                ('slug', models.SlugField(blank=True, max_length=160, null=True, unique=True, verbose_name='URL of movie')),
                ('MetaKeyWords', models.CharField(max_length=500, verbose_name='MetKeyWords of video')),
                ('MetaDescriptions', models.CharField(max_length=500, verbose_name='MetaDescription of video')),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('is_published', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of published')),
                ('is_published_update', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='category_video', to='main.videocategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-id'],
            },
        ),
    ]
