# Generated by Django 4.1.1 on 2022-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_videocategory_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='MetaDescriptions_az',
            field=models.CharField(max_length=500, null=True, verbose_name='MetaDescription of video'),
        ),
        migrations.AddField(
            model_name='video',
            name='MetaDescriptions_en',
            field=models.CharField(max_length=500, null=True, verbose_name='MetaDescription of video'),
        ),
        migrations.AddField(
            model_name='video',
            name='MetaDescriptions_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='MetaDescription of video'),
        ),
        migrations.AddField(
            model_name='video',
            name='MetaKeyWords_az',
            field=models.CharField(max_length=500, null=True, verbose_name='MetKeyWords of video'),
        ),
        migrations.AddField(
            model_name='video',
            name='MetaKeyWords_en',
            field=models.CharField(max_length=500, null=True, verbose_name='MetKeyWords of video'),
        ),
        migrations.AddField(
            model_name='video',
            name='MetaKeyWords_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='MetKeyWords of video'),
        ),
        migrations.AddField(
            model_name='video',
            name='descriptions_az',
            field=models.TextField(null=True, verbose_name='Description of Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='descriptions_en',
            field=models.TextField(null=True, verbose_name='Description of Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='Description of Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='tagline_az',
            field=models.CharField(default='', max_length=360, null=True, verbose_name='Tagline of Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='tagline_en',
            field=models.CharField(default='', max_length=360, null=True, verbose_name='Tagline of Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='tagline_ru',
            field=models.CharField(default='', max_length=360, null=True, verbose_name='Tagline of Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_az',
            field=models.CharField(max_length=155, null=True, verbose_name='Title of Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Title of Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Title of Video'),
        ),
        migrations.AddField(
            model_name='videocategory',
            name='descriptions_az',
            field=models.TextField(null=True, verbose_name='Description of VideoCategory'),
        ),
        migrations.AddField(
            model_name='videocategory',
            name='descriptions_en',
            field=models.TextField(null=True, verbose_name='Description of VideoCategory'),
        ),
        migrations.AddField(
            model_name='videocategory',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='Description of VideoCategory'),
        ),
        migrations.AddField(
            model_name='videocategory',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of VideoCategory'),
        ),
        migrations.AddField(
            model_name='videocategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of VideoCategory'),
        ),
        migrations.AddField(
            model_name='videocategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of VideoCategory'),
        ),
    ]
