# Generated by Django 4.1.1 on 2022-10-04 10:50

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_video_metadescriptions_az_video_metadescriptions_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservices',
            name='image',
            field=models.ImageField(upload_to='static/ourservices/', verbose_name='Poster of ourservices articles'),
        ),
        migrations.AlterField(
            model_name='ourservicescategory',
            name='image',
            field=models.ImageField(upload_to='static/about_category/', verbose_name='Image of AboutCategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='static/Image//%Y/%m/%d', verbose_name='Poster of DetailView'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_tur',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpeg', force_format=None, keep_meta=True, quality=75, scale=None, size=[200, 200], upload_to='static/Image_Tur//%Y/%m/%d', verbose_name='Poster of ListView'),
        ),
    ]
